name: Trigger Jenkins on Mention

on:
  issue_comment:
    types: [created]

jobs:
  trigger-jenkins:
    if: github.event.issue.pull_request != null && contains(github.event.comment.body, '@Dotnet-s390x') 
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Jenkins Build via cURL
        run: |
          curl -X POST "http://148.100.85.217:8080/generic-webhook-trigger/invoke?token=mysecret123" \
            -H "Content-Type: application/json" \
            -d @- <<EOF
          {
            "repository": "${{ github.repository }}",
            "pr_number": "${{ github.event.issue.number }}",
            "comment": "${{ github.event.comment.body }}",
            "sender": "${{ github.event.comment.user.login }}"
          }
          EOF
