name: Trigger Jenkins on Mention

on:
  issue_comment:
    types: [created]

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest
    if: github.event.comment.body != '' && contains(github.event.comment.body, '@Dotnet-s390x')
    steps:
      - name: Send Webhook to Jenkins
        run: |
          curl -X POST "${{ env.JENKINS_URL }}/generic-webhook-trigger/invoke?token=mysecret123" \
            --data-urlencode "comment=${{ github.event.comment.body }}" \
            --data-urlencode "pr_number=${{ github.event.issue.number }}" \
            --data-urlencode "repository=${{ github.repository }}" \
            --data-urlencode "sender=${{ github.event.comment.user.login }}"
        env:
          JENKINS_URL: http://148.100.85.217:8080
