name: Trigger Jenkins on PR Comment

on:
  issue_comment:
    types: [created]

jobs:
  send-to-jenkins:
    if: github.event.issue.pull_request != null && contains(github.event.comment.body, '@Dotnet-s390x')
    runs-on: ubuntu-latest
    steps:
      - name: Send webhook to Jenkins
        run: |
          curl -X POST "http://148.100.85.217:8080/generic-webhook-trigger/invoke?token=mysecret123" \
          -H "Content-Type: application/json" \
          -d '{
                "pr_number": "'${{ github.event.issue.number }}'",
                "comment_body": "'${{ github.event.comment.body }}'",
                "comment_user": "'${{ github.event.comment.user.login }}'"
              }'
